name: zaczatek_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  cupertino_icons: ^1.0.8
  csv: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.20.2
  table_calendar: ^3.0.9
  google_fonts: ^6.2.0
  supabase_flutter: ^2.9.1
  uuid: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/zaczatek.jpg
